services:
  - type: web
    name: galactiturf-backend
    runtime: python
    plan: free
    rootDir: backend/
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn galactiturf.wsgi:application --settings=galactiturf.settings_production
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: galactiturf-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://galactiturf.vercel.app
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: DATABASE_URL
        value: postgresql://postgres.kdzakhdgdbhxijxugywa:[HnQ6v5ozHuyTY5WQ]@aws-0-eu-west-2.pooler.supabase.com:6543/postgres
