# Generated by Django 4.2.7 on 2025-08-01 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the football game', max_length=200)),
                ('location', models.CharField(help_text='Location/venue of the game', max_length=500)),
                ('date_time', models.DateTimeField(help_text='Date and time of the game')),
                ('coin_price', models.PositiveIntegerField(help_text='Price in coins to book this game', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_slots', models.PositiveIntegerField(help_text='Total number of available slots', validators=[django.core.validators.MinValueValidator(1)])),
                ('booked_slots', models.PositiveIntegerField(default=0, help_text='Number of slots already booked', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the game', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the game')),
                ('rules', models.TextField(blank=True, help_text='Rules and guidelines for the game')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_paid', models.PositiveIntegerField(help_text='Number of coins paid for this booking', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', help_text='Status of the booking', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the booking was made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the booking')),
                ('game', models.ForeignKey(help_text='Game that was booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='games.game')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
