# Generated by Django 4.2.7 on 2025-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in NGN', max_digits=10)),
                ('coins_awarded', models.IntegerField(help_text='Number of coins awarded for this subscription')),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(default=30, help_text='Duration of subscription in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
