# Generated by Django 4.2.7 on 2025-08-01 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subscription tier', max_length=50, unique=True)),
                ('tier_type', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], help_text='Type of subscription tier', max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coins_awarded', models.PositiveIntegerField(help_text='Number of coins awarded with this subscription', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Description of the subscription tier')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'ordering': ['price'],
            },
        ),
    ]
