# Generated by Django 4.2.7 on 2025-08-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription'), ('booking', 'Game Booking'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN', max_digits=10)),
                ('coins_amount', models.IntegerField(help_text='Amount in coins')),
                ('reference_id', models.CharField(help_text='Paystack reference ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paystack_response', models.JSONField(default=dict, help_text='Full Paystack response')),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
