# Generated by Django 4.2.7 on 2025-08-01 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription Purchase'), ('booking', 'Game Booking'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in local currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coins_involved', models.PositiveIntegerField(default=0, help_text='Number of coins involved in the transaction')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the transaction', max_length=20)),
                ('reference_id', models.CharField(help_text='Paystack reference ID', max_length=100, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, help_text='Paystack transaction ID', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the transaction')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from Paystack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
